import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    products: 'Products',
    inventory: 'Inventory',
    expenses: 'Expenses',
    accounting: 'Accounting',
    suppliers: 'Suppliers',
    customers: 'Customers',
    createInvoice: 'Create Invoice',
    createQuotation: 'Create Quotation',
    invoiceHistory: 'Invoice History',
    quotationHistory: 'Quotation History',
    orderManagement: 'Order Management',
    ordersHistory: 'Orders History',
    label: 'Label',
    reports: 'Reports',
    procurement: 'Procurement',
    userManagement: 'User Management',
    systemPreferences: 'System Preferences',
    labelGeneration: 'Label Generation',
    logout: 'Logout',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    import: 'Import',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    all: 'All',
    granted: 'Granted',
    denied: 'Denied',
    configure: 'Configure',
    remove: 'Remove',
    access: 'Access',
    actions: 'Actions',
    module: 'Module',
    nearExpiry: 'Near Expiry',
    editCategory: 'Edit Category',
    makeCategoryChanges: 'Make changes to the category details below.',
    semiRaw: 'Semi-Raw',
    rawMaterial: 'Raw Material',
    semiRawMaterial: 'Semi-Raw Material',
    finishedProduct: 'Finished Product',
    grade: 'Grade',
    pharmaceutical: 'Pharmaceutical (P)',
    food: 'Food (F)',
    technical: 'Technical (T)',
    active: 'Active',
    inactive: 'Inactive',
    discontinued: 'Discontinued',
    warehouse: 'Warehouse',
    storageRoom: 'Storage Room',
    coldStorage: 'Cold Storage',
    quarantine: 'Quarantine',
    importingProducts: 'Importing Products',
    processing: 'Processing',
    importComplete: 'Import Complete',
    successfullyImported: 'Successfully imported',
    
    // Profile & Settings
    profile: 'Profile',
    settings: 'Settings',
    
    // Permission Management
    moduleAccessControl: 'Module Access Control',
    totalModulesAvailable: 'Total Modules Available',
    permissionGranted: 'Permission Granted',
    permissionRemoved: 'Permission Removed',
    accessGrantedToModule: 'Access granted to module',
    accessRemovedFromModule: 'Access removed from module',
    failedToGrantPermission: 'Failed to grant permission',
    failedToRemovePermission: 'Failed to remove permission',
    confirmDeleteUser: 'Are you sure you want to delete this user?',
    
    // Module Descriptions
    dashboardDesc: 'Main dashboard overview and analytics',
    inventoryDesc: 'Inventory management and stock tracking',
    expensesDesc: 'Expense tracking and management',
    accountingDesc: 'Financial management and reports',
    suppliersDesc: 'Supplier management and relationships',
    customersDesc: 'Customer relationship management',
    createInvoiceDesc: 'Invoice creation and management',
    createQuotationDesc: 'Quotation generation and pricing',
    invoiceHistoryDesc: 'View and manage invoice history',
    quotationHistoryDesc: 'View quotation records and history',
    orderManagementDesc: 'Order processing and tracking',
    ordersHistoryDesc: 'Historical order data and records',
    labelGeneratorDesc: 'Generate product and shipping labels',
    reportsDesc: 'Business reports and analytics',
    procurementDesc: 'Procurement and purchasing management',
    userManagementDesc: 'Manage user accounts and roles',
    systemPreferencesDesc: 'System configuration and settings',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    
    // Financial
    totalAssets: 'Total Assets',
    totalLiabilities: 'Total Liabilities',
    monthlyRevenue: 'Monthly Revenue',
    monthlyExpenses: 'Monthly Expenses',
    
    // Company
    companyName: 'Morgan Chemical ERP',
    
    // Inventory Management
    inventoryManagement: 'Inventory Management',
    addItem: 'Add Item',
    selectWarehouse: 'Select Warehouse',
    selectedWarehouse: 'Selected Warehouse',
    allWarehouses: 'All Warehouses',
    allStock: 'All Stock',
    importCsv: 'Import CSV',
    exportCsv: 'Export CSV',
    createLabels: 'Create Labels',
    inventorySettings: 'Inventory Settings',
    warehouseSelector: 'Warehouse Selector',
    addWarehouse: 'Add Warehouse',
    editWarehouse: 'Edit Warehouse',
    allStock: 'All Stock',
    viewingInventory: 'Viewing inventory across',
    allWarehouses: 'all warehouses',
    viewingInventoryFor: 'Viewing inventory for',
    inventoryModule: 'Inventory',
    categories: 'Categories',
    searchInventory: 'Search inventory...',
    filterByStatus: 'Filter by status',
    filterByCategory: 'Filter by category',
    allStatuses: 'All Statuses',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    expired: 'Expired',
    allCategories: 'All Categories',
    productItem: 'Product',
    category: 'Category',
    batchNo: 'Batch No.',
    gs1Code: 'GS1 Code',
    type: 'Type',
    quantity: 'Quantity',
    description: 'Description',
    location: 'Location',
    shelf: 'Shelf',
    price: 'Price',
    expiryDate: 'Expiry Date',
    actions: 'Actions',
    createLabel: 'Create Label',
    showHistory: 'Show History',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    noProductsFound: 'No products found',
    tryAdjustingFilters: 'Try adjusting your filters',
    addFirstProduct: 'Add your first product to get started',
    addProduct: 'Add Product',
    
    // Dialog translations
    editProductInfo: 'Edit Product Information',
    addNewProduct: 'Add New Product',
    updateProductDetails: 'Update comprehensive product details and inventory information',
    registerNewProduct: 'Register a new pharmaceutical product with complete details and specifications',
    productHistory: 'Product History & Analytics',
    comprehensiveHistory: 'Comprehensive history and performance analytics for',
    loadingProductDetails: 'Loading product details...',
    
    // Inventory Settings Dialog
    configureInventoryOptions: 'Configure Inventory Dropdown Options',
    manageDropdownOptions: 'Manage the options available in Units of Measure, Product Types, Status Options, and Location Types dropdowns.',
    unitsOfMeasure: 'Units of Measure',
    itemTypes: 'Item Types',
    statusOptions: 'Status Options',
    locationTypes: 'Location Types',
    newUnitPlaceholder: 'New unit (e.g., mL, tablets)',
    newItemTypePlaceholder: 'New item type',
    newStatusPlaceholder: 'New status option',
    newLocationPlaceholder: 'New location type',
    done: 'Done',
    
    // Additional ProductForm translations
    chemicalName: 'Chemical Name',
    
    // Warehouse Dialogs
    editWarehouseDialog: 'Edit Warehouse',
    addNewWarehouse: 'Add New Warehouse',
    updateWarehouseDetails: 'Update the details for this warehouse',
    enterWarehouseDetails: 'Enter the details for the new warehouse',
    warehouseName: 'Name',
    warehouseLocation: 'Location',
    warehouseNamePlaceholder: 'Warehouse name',
    warehouseLocationPlaceholder: 'Warehouse location',
    warehouseUpdated: 'Warehouse updated',
    warehouseUpdatedSuccess: 'The warehouse details have been updated successfully.',
    warehouseAdded: 'Warehouse added',
    warehouseAddedSuccess: 'The new warehouse has been added successfully.',
    saveChanges: 'Save Changes',
    addWarehouseBtn: 'Add Warehouse',
    transferProductToWarehouse: 'Transfer Product to Another Warehouse',
    transferStockDescription: 'Transfer stock from the current warehouse to a different warehouse location',
    productDetails: 'Product Details',
    productName: 'Product',
    currentStock: 'Current Stock',
    currentWarehouse: 'Current Warehouse',
    unknown: 'Unknown',
    targetWarehouse: 'Target Warehouse',
    selectTargetWarehouse: 'Select target warehouse',
    transferQuantity: 'Transfer Quantity',
    enterQuantityToTransfer: 'Enter quantity to transfer',
    maximum: 'Maximum',
    transferNotesOptional: 'Transfer Notes (Optional)',
    addTransferNotes: 'Add any notes about this transfer...',
    transferInitiated: 'Transfer Initiated',
    transferringProduct: 'Transferring',
    from: 'from',
    to: 'to',
    confirmTransfer: 'Confirm Transfer',
    
    // Product History Dialog
    productInformation: 'Product Information',
    skuCode: 'SKU Code',
    manufacturer: 'Manufacturer',
    inventoryDetails: 'Inventory Details',
    currentQuantity: 'Current Quantity',
    inventoryWarehouseLocation: 'Warehouse Location',
    mainWarehouse: 'Main Warehouse',
    reorderLevel: 'Reorder Level',
    stockValue: 'Stock Value',
    lastStockMovement: 'Last Stock Movement',
    unitsReceived: 'units received on',
    averageMonthlyUsage: 'Average Monthly Usage',
    month: 'month',
    pricingInformation: 'Pricing Information',
    profitMargin: 'Profit Margin',
    profitPerUnit: 'Profit per Unit',
    lastPriceUpdate: 'Last Price Update',
    priceTrend: 'Price Trend',
    increasing: 'Increasing',
    complianceQuality: 'Compliance & Quality',
    batchNumber: 'Batch Number',
    qualityStatus: 'Quality Status',
    approved: 'Approved',
    lastQualityCheck: 'Last Quality Check',
    regulatoryStatus: 'Regulatory Status',
    edaApproved: 'EDA Approved - License',
    activityTimeline: 'Activity Timeline',
    productInfoUpdated: 'Product Information Updated',
    quantityChanged: 'Quantity changed from 150 to',
    updatedBy: 'Updated by: System Administrator',
    stockReceived: 'Stock Received',
    receivedUnits: 'Received',
    fromSupplier: 'from supplier',
    purchaseOrder: 'Purchase Order',
    labelGenerated: 'Label Generated',
    productLabelCreated: 'Product label created for batch',
    labelType: 'Label Type: Pharmaceutical Grade',
    productAddedInventory: 'Product Added to Inventory',
    initialStock: 'Initial stock',
    createdBy: 'Created by: Inventory Manager',
    close: 'Close',
    exportReport: 'Export Report',
    transferToWarehouse: 'Transfer to Warehouse',
    editProduct: 'Edit Product',
    
    // Categories Management
    'Manage product categories used in inventory and sales': 'Manage product categories used in inventory and sales',
    'No categories found': 'No categories found',
    'Add your first category below': 'Add your first category below',
    'Name': 'Name',
    'Description': 'Description',
    'Category Name': 'Category Name',
    'Description (optional)': 'Description (optional)',
    'Adding...': 'Adding...',
    'Add Category': 'Add Category',
    'Confirm Deletion': 'Confirm Deletion',
    'Are you sure you want to delete the category': 'Are you sure you want to delete the category',
    'This action cannot be undone': 'This action cannot be undone',
    'Cancel': 'Cancel',
    'Deleting...': 'Deleting...',
    'Delete': 'Delete',
    'manageCategories': 'Manage Categories',
    'more': 'more',
    'categoriesDescription': 'Click "Manage Categories" to add, edit, or delete product categories',
    
    // Create Invoice
    createInvoiceModule: 'Create Invoice',
    invoiceManagement: 'Invoice Management',
    createNewInvoicesAndManageDrafts: 'Create new invoices and manage your drafts',
    customerInfo: 'Customer Information',
    chooseCustomer: 'Choose Customer',
    customerName: 'Customer Name',
    company: 'Company',
    position: 'Position',
    emailInvoice: 'Email',
    phoneInvoice: 'Phone',
    sectorInvoice: 'Sector',
    addressInvoice: 'Address',
    taxNumberInvoice: 'Tax Number',
    invoiceItems: 'Invoice Items',
    selectProduct: 'Select Product',
    invoiceProductName: 'Product Name',
    unitPrice: 'Unit Price',
    total: 'Total',
    addInvoiceItem: 'Add Item',
    removeItem: 'Remove Item',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    taxRate: 'Tax Rate (%)',
    taxAmount: 'Tax Amount',
    vat: 'VAT',
    vatRate: 'VAT Rate (%)',
    vatAmount: 'VAT Amount',
    grandTotal: 'Grand Total',
    paymentInfo: 'Payment Information',
    paymentStatus: 'Payment Status',
    paymentMethod: 'Payment Method',
    amountPaid: 'Amount Paid',
    generateInvoice: 'Generate Invoice',
    printInvoice: 'Print Invoice',
    downloadPdf: 'Download PDF',
    paid: 'Paid',
    unpaid: 'Unpaid',
    partial: 'Partial',
    cash: 'Cash',
    visa: 'Visa',
    cheque: 'Cheque',
    bankTransfer: 'Bank Transfer',
    etaNumber: 'ETA Number',
    
    // Dashboard
    welcomeToPremier: 'Welcome to Premier ERP',
    yourBusinessOverview: 'Your business overview',
    financialSummary: 'Financial Summary',
    operationalMetrics: 'Operational Metrics',
    inventoryAlerts: 'Inventory Alerts',
    salesOverview: 'Sales Overview',
    salesDistribution: 'Sales Distribution',
    categoryPerformance: 'Category Performance',
    totalRevenue: 'Total Revenue',
    totalExpenses: 'Total Expenses',
    netProfit: 'Net Profit',
    cashBalance: 'Cash Balance',
    pendingOrders: 'Pending Orders',
    outstandingAR: 'Outstanding A/R',
    totalAccounts: 'Total Accounts',
    trialBalance: 'Trial Balance',
    lowStockItems: 'Low Stock Items',
    expiringProducts: 'Expiring Products',
    warehouseBreakdown: 'Warehouse Breakdown',
    viewDetails: 'View Details',
    
    // Expiring Products Card
    expired: 'Expired',
    expiring: 'Expiring',
    expiresToday: 'Expires today',
    expiresTomorrow: 'Expires tomorrow',
    daysLeft: '{days} days left',
    noExpiry: 'No expiry',
    errorLoadingExpiryData: 'Error Loading Expiry Data',
    unableToLoadExpiry: 'Unable to load expiry information. Please try again later.',
    noProductsExpiringSoon: 'No products expiring soon!',
    stock: 'Stock',
    showLess: 'Show Less',
    showAllItems: 'Show All {count} Items',
    
    // Low Stock Card
    lowStockProducts: 'Low Stock Products',
    lowStockAlert: 'Low Stock Alert',
    errorLoadingStockData: 'Error Loading Stock Data',
    unableToLoadStock: 'Unable to load stock information. Please try again later.',
    outOfStock: 'Out',
    low: 'Low',
    allProductsWellStocked: 'All products are well stocked!',
    reorder: 'Reorder',
    
    // Dashboard Chart Dialogs
    salesOverviewEnhanced: 'Sales Overview - Enhanced View',
    salesAnalytics: 'Sales Analytics',
    peakMonth: 'Peak Month',
    december: 'December',
    sales: 'Sales',
    growthRate: 'Growth Rate',
    yoy: 'YoY',
    trendingUp: 'Trending Up',
    average: 'Average',
    monthly: 'Monthly',
    targetMet: 'Target Met',
    thisYear: 'This Year',
    target: 'Target',
    salesDistributionEnhanced: 'Sales Distribution - Enhanced View',
    distributionDetails: 'Distribution Details',
    categoryPerformanceEnhanced: 'Category Performance - Enhanced View',
    performanceMetrics: 'Performance Metrics',
    vsLastMonth: 'vs Last Month',
    
    // Accounting Module
    accountingDashboard: 'Accounting Dashboard',
    chartOfAccounts: 'Chart of Accounts',
    journalEntries: 'Journal Entries',
    customerPayments: 'Customer Payments',
    profitAndLoss: 'Profit & Loss',
    balanceSheet: 'Balance Sheet',
    trialBalanceReport: 'Trial Balance Report',
    accountingPeriods: 'Accounting Periods',
    financialIntegration: 'Financial Integration',
    
    // Expenses Module
    expenseManagement: 'Expense Management',
    addExpense: 'Add Expense',
    expenseCategory: 'Expense Category',
    expenseAmount: 'Amount',
    expenseDate: 'Date',
    expenseDescription: 'Description',
    paymentMethodExpense: 'Payment Method',
    costCenter: 'Cost Center',
    receiptUpload: 'Receipt Upload',
    expenseStatus: 'Expense Status',
    
    // Reports Module
    reportsAnalytics: 'Reports & Analytics',
    inventoryReports: 'Inventory Reports',
    salesReports: 'Sales Reports',
    financialReports: 'Financial Reports',
    customerReports: 'Customer Reports',
    supplierReports: 'Supplier Reports',
    exportReport: 'Export Report',
    generateReport: 'Generate Report',
    reportPeriod: 'Report Period',
    
    // Procurement Module
    procurementManagement: 'Procurement Management',
    createPurchaseOrder: 'Create Purchase Order',
    purchaseOrderHistory: 'Purchase Order History',
    selectSupplier: 'Select Supplier',
    expectedDelivery: 'Expected Delivery',
    procurementStatus: 'Procurement Status',
    approvalRequired: 'Approval Required',
    
    // Order Management
    orderManagementSystem: 'Order Management System',
    newOrder: 'New Order',
    orderStatus: 'Order Status',
    orderNumber: 'Order Number',
    orderDate: 'Order Date',
    deliveryDate: 'Delivery Date',
    orderTotal: 'Order Total',
    
    // User Management
    userManagementSystem: 'User Management System',
    addUser: 'Add User',
    userName: 'User Name',
    userEmail: 'Email',
    userRole: 'User Role',
    userStatus: 'User Status',
    userPermissions: 'User Permissions',
    lastLogin: 'Last Login',
    manageSystemUsers: 'Manage system users and their permissions',
    createUser: 'Create User',
    createNewUser: 'Create New User',
    username: 'Username',
    fullName: 'Full Name',
    email: 'Email',
    password: 'Password',
    role: 'Role',
    status: 'Status',
    enterUsername: 'Enter username',
    enterFullName: 'Enter full name',
    enterEmail: 'Enter email address',
    enterPassword: 'Enter password',
    selectRole: 'Select role',
    selectStatus: 'Select status',
    admin: 'Admin',
    manager: 'Manager',
    staff: 'Staff',
    accountant: 'Accountant',
    inventoryManager: 'Inventory Manager',
    salesRep: 'Sales Representative',
    suspended: 'Suspended',
    systemUsers: 'System Users',
    user: 'User',
    permissions: 'Permissions',
    actions: 'Actions',
    allModules: 'All Modules',
    modules: 'Modules',
    managePermissions: 'Manage Permissions',
    grantAllPermissions: 'Grant All Permissions',
    revokeAllPermissions: 'Revoke All Permissions',
    granted: 'Granted',
    denied: 'Denied',
    adminAccess: 'Admin Access',
    userCreatedSuccessfully: 'User created successfully',
    userDeletedSuccessfully: 'User deleted successfully',
    failedToCreateUser: 'Failed to create user',
    failedToDeleteUser: 'Failed to delete user',
    permissionUpdatedSuccessfully: 'Permission updated successfully',
    permissionRemovedSuccessfully: 'Permission removed successfully',
    failedToUpdatePermission: 'Failed to update permission',
    failedToRemovePermission: 'Failed to remove permission',
    cannotDeleteYourself: 'Cannot delete your own account',
    creating: 'Creating...',
    create: 'Create',
    accessDenied: 'Access Denied',
    noPermissionForModule: 'You do not have permission to access this module',
    contactAdminForAccess: 'Contact your administrator for access',
    
    // System Preferences
    systemPreferencesTitle: 'System Preferences',
    companySettings: 'Company Settings',
    currencySettings: 'Currency Settings',
    taxSettings: 'Tax Settings',
    notificationSettings: 'Notification Settings',
    backupSettings: 'Backup Settings',
    securitySettings: 'Security Settings',
    
    // Common Actions
    view: 'View',
    create: 'Create',
    update: 'Update',
    deleteAction: 'Delete',
    confirm: 'Confirm',
    cancelAction: 'Cancel',
    saveChanges: 'Save Changes',
    discardChanges: 'Discard Changes',
    refresh: 'Refresh',
    print: 'Print',
    download: 'Download',
    upload: 'Upload',
    
    // Status Messages
    successMessage: 'Operation successful',
    errorMessage: 'An error occurred',
    loadingMessage: 'Loading...',
    savingMessage: 'Saving...',
    deletingMessage: 'Deleting...',
    noDataFound: 'No data found',
    
    // Time periods
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    lastWeek: 'Last Week',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    thisYear: 'This Year',
    lastYear: 'Last Year',
    customRange: 'Custom Range',
    
    // Dashboard additions
    currentMonthRevenue: 'Current month revenue',
    revenueMinusExpenses: 'Revenue minus expenses',
    pendingInvoices: 'pending invoices',
    ordersPending: 'orders pending',
    expenseEntries: 'expense entries',
    availableCashFlow: 'Available cash flow',
    paymentsReceived: 'Payments Received',
    thisMonthPayments: 'This month payments',
    inventoryValue: 'Inventory Value',
    costValue: 'Cost value',
    selling: 'Selling',
    warehouses: 'warehouses',
    newThisMonth: 'new this month',
    fromLastMonth: 'from last month',
    calculatingTrends: 'Calculating trends...',
    todaySales: 'Today Sales',
    daily: 'Daily',
    monthSales: 'Month Sales',
    monthly: 'Monthly',
    collectedTax: 'Collected Tax',
    vatCollectedFromSales: 'VAT collected from sales',
    salesOverview: 'Sales Overview',
    salesDistribution: 'Sales Distribution',
    categoryPerformance: 'Category Performance',
    inventoryValueBreakdown: 'Inventory Value Breakdown',
    realTimeWarehouseAnalysis: 'Real-time warehouse inventory analysis',
    loadingWarehouseBreakdown: 'Loading warehouse breakdown',
    totalCostValue: 'Total Cost Value',
    totalSellingValue: 'Total Selling Value',
    totalQuantity: 'Total Quantity',
    units: 'units',
    sellingValue: 'Selling Value',
    avgUnitCost: 'Avg Unit Cost',
    
    // OrdersHistory page
    ordersHistory: 'Orders History',
    productionAndRefiningOrderTracking: 'Production and refining order tracking',
    totalOrders: 'Total Orders',
    activeProductionOrders: 'Active production orders',
    totalRevenue: 'Total Revenue',
    fromCompletedOrders: 'From completed orders',
    totalCosts: 'Total Costs',
    productionExpenses: 'Production expenses',
    netProfit: 'Net Profit',
    margin: 'margin',
    noData: 'No data',
    filtersAndSearch: 'Filters & Search',
    searchOrders: 'Search orders...',
    filterByStatus: 'Filter by status',
    allStatuses: 'All Statuses',
    completed: 'Completed',
    inProgress: 'In Progress',
    cancelled: 'Cancelled',
    filterByType: 'Filter by type',
    allTypes: 'All Types',
    production: 'Production',
    manufacturing: 'Manufacturing',
    refining: 'Refining',
    exportCSV: 'Export CSV',
    loadingOrderHistory: 'Loading order history...',
    orderHistory: 'Order History',
    orders: 'orders',
    orderNumber: 'Order #',
    batchNumber: 'Batch #',
    type: 'Type',
    customer: 'Customer',
    product: 'Product',
    status: 'Status',
    revenue: 'Revenue',
    profit: 'Profit',
    actions: 'Actions',
    viewDetails: 'View Details',
    downloadReport: 'Download Report',
    orderDetails: 'Order Details',
    completeInformationForBatch: 'Complete information for batch',
    orderInformation: 'Order Information',
    targetProduct: 'Target Product',
    customerInformation: 'Customer Information',
    customerName: 'Customer Name',
    company: 'Company',
    timeline: 'Timeline',
    orderDate: 'Order Date',
    completionDate: 'Completion Date',
    financialSummary: 'Financial Summary',
    totalCost: 'Total Cost',
    profitMargin: 'Profit Margin',
    additionalCosts: 'Additional Costs',
    transportation: 'Transportation',
    labor: 'Labor',
    equipment: 'Equipment',
    qualityControl: 'Quality Control',
    storage: 'Storage',
    totalAdditional: 'Total Additional',
    rawMaterialsUsed: 'Raw Materials Used',
    exportReport: 'Export Report',
    exportAsPDF: 'Export as PDF',
    exportAsExcel: 'Export as Excel',
    printReport: 'Print Report',
    generateInvoice: 'Generate Invoice',
    showing: 'Showing',
    to: 'to',
    of: 'of',
    orders: 'orders',
    previous: 'Previous',
    next: 'Next',
    
    // Login page
    signInToAccount: 'Sign in to your account',
    welcomeBack: 'Welcome Back',
    signInPrompt: 'Sign in to your Premier ERP account',
    email: 'Email',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPassword: 'Enter your password',
    signIn: 'Sign In',
    secureERPSystem: 'Secure Premier ERP system',
    enterpriseSecurity: 'Enterprise Security',
    termsAndPrivacy: 'By signing in, you agree to our Terms of Service and Privacy Policy',
    
    // Customer Management
    customerRecords: 'Customer Records',
    allCustomers: 'All Customers',
    activeCustomers: 'Active Customers',
    inactiveCustomers: 'Inactive Customers',
    viewProfile: 'View Profile',
    viewOrders: 'View Orders',
    editCustomer: 'Edit Customer',
    deleteCustomer: 'Delete Customer',
    customerDeleted: 'Customer deleted successfully',
    importCustomers: 'Import Customers',
    exportCustomers: 'Export Customers',
    addCustomer: 'Add Customer',
    searchCustomers: 'Search customers by name, email or phone',
    filterByStatus: 'Filter by Status',
    showingResults: 'Showing results',
    noCustomersFound: 'No customers found',
    tryDifferentSearch: 'Try adjusting your search criteria',
    loadingCustomers: 'Loading customers...',
    
    // Customer Analytics
    reportsAnalytics: 'Reports & Analytics',
    totalCustomers: 'Total Customers',
    active: 'Active',
    newThisMonth: 'New This Month',
    avgOrderValue: 'Avg Order Value',
    perCustomer: 'Per customer',
    repeatCustomers: 'Repeat Customers',
    retentionRate: 'Retention rate',
    customerDistributionBySector: 'Customer Distribution by Sector',
    topCustomersByRevenue: 'Top Customers by Revenue',
    geographicDistribution: 'Geographic Distribution',
    customers: 'customers',
    
    // Additional Customer Page translations
    customerManagement: 'Customer Management',
    manageClients: 'Manage Clients',
    activeSectors: 'Active Sectors',
    industryTypes: 'Industry Types',
    customerValue: 'Customer Value',
    totalPortfolio: 'Total Portfolio',
    recentAdditions: 'Recent Additions',
    topSector: 'Top Sector',
    geographicSpread: 'Geographic Spread',
    cities: 'Cities',
    coverageArea: 'Coverage Area',
    monthlyIncrease: 'Monthly Increase',
    errorLoadingCustomers: 'Error loading customers',
    pleaseTryAgainLater: 'Please try again later',
    noMatchingCustomersFound: 'No matching customers found',
    tryAdjustingSearchQuery: 'Try adjusting your search query',
    noCustomersAvailable: 'No customers available',
    action: 'Action',
    customerReportsAnalytics: 'Customer Reports & Analytics',
    comprehensiveReportsInsights: 'Comprehensive reports and insights',
    exportPDF: 'Export PDF',
    loadingReports: 'Loading reports...',
    customerRevenue: 'Customer Revenue',
    monthlyGrowthTrend: 'Monthly Growth Trend',
    activeAccounts: 'Active Accounts',
    
    // Add Customer Dialog
    addNewCustomer: 'Add New Customer',
    createComprehensiveCustomerDetails: 'Create comprehensive customer details and business relationship information',
    customerInformation: 'Customer Information',
    customerNameRequired: 'Customer Name *',
    fullCustomerName: 'Full customer name',
    positionTitle: 'Position/Title',
    jobTitlePosition: 'Job title or position',
    customerStatus: 'Customer Status',
    activeCustomer: 'Active Customer',
    inactiveCustomer: 'Inactive Customer',
    prospect: 'Prospect',
    vipCustomer: 'VIP Customer',
    companyInformation: 'Company Information',
    fullCompanyName: 'Full company name',
    industrySector: 'Industry Sector',
    selectIndustrySector: 'Select industry sector',
    contactInformation: 'Contact Information',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    addressTaxInformation: 'Address & Tax Information',
    completeAddress: 'Complete Address',
    customerAddress: 'Customer address',
    taxNumberEta: 'Tax Number (ETA Registration)',
    enterTaxNumber: 'Enter Egyptian Tax Authority registration number',
    requiredForEta: 'Required for invoices to appear in customer\'s ETA portal',
    
    // Create Invoice page
    draftInvoices: 'Draft Invoices',
    createNewInvoice: 'Create New Invoice',
    createInvoiceDescription: 'Create a new invoice by selecting a customer and adding products',
    saveAsDraft: 'Save as Draft',
    previewInvoice: 'Preview Invoice',
    invoicesInProgress: 'Invoices In Progress',
    resetToInvoice1: 'Reset to Invoice 1',
    newInvoice: 'New Invoice',
    invoiceProgressAutoSaved: 'Your invoice progress is automatically saved. You can work on up to 4 invoices at the same time.',
    nextInvoiceNumber: 'Next Invoice #',
    customerInformation: 'Customer Information',
    selectOrCreateCustomer: 'Select an existing customer or create a new one',
    customer: 'Customer',
    selectCustomer: 'Select customer...',
    searchCustomer: 'Search customer...',
    noCustomersFoundFor: 'No customers found for',
    createNewCustomer: 'Create New Customer',
    typeToSearchCustomers: 'Type to search customers...',
    paperInvoiceNumber: 'Paper Invoice Number',
    paperInvoiceNumberPlaceholder: 'P-2025001',
    physicalInvoiceReference: 'Physical invoice reference number for record-keeping',
    approvalNumber: 'Approval No.',
    approvalNumberPlaceholder: 'APP-2025001',
    internalApprovalReference: 'Internal approval reference number',
    code: 'Code',
    mobile: 'Mobile',
    etaNumber: 'ETA Number',
    sector: 'Sector',
    email: 'Email',
    address: 'Address',
    emailPlaceholder: 'customer@example.com',
    addressPlaceholder: 'Customer address',
    draftSaved: 'Draft Saved',
    invoiceSavedAsDraft: 'Invoice has been saved as draft successfully',
    newCustomer: 'New Customer',
    companyName: 'Company Name',
    companyNamePlaceholder: 'Company name',
    name: 'Name',
    customerNamePlaceholder: 'Customer name',
    position: 'Position',
    jobTitlePositionPlaceholder: 'Job title/Position',
    phone: 'Phone',
    phoneNumberPlaceholder: 'Phone number',
    businessSectorPlaceholder: 'Business sector',
    taxNumberEtaRegistration: 'Tax Number (ETA Registration)',
    egyptianTaxAuthorityPlaceholder: 'Egyptian Tax Authority registration number',
    requiredForEtaPortal: 'Required for invoices to appear in customer\'s ETA portal',
    customerEmailPlaceholder: 'customer@example.com',
    customerAddressPlaceholder: 'Customer address',
    saveCustomer: 'Save Customer',
    invoiceItems: 'Invoice Items',
    addProductsToInvoice: 'Add products to this invoice',
    
    // Invoice Preview and Print translations
    invoicePreview: 'Invoice Preview',
    printInvoice: 'Print Invoice',
    printPreview: 'Print Preview',
    closePreview: 'Close Preview',
    previewInvoiceBeforePrinting: 'Preview invoice before printing or downloading',
    print: 'Print',
    downloadPDF: 'Download PDF',
    generating: 'Generating...',
    invoice: 'Invoice',
    invoiceNumber: 'Invoice Number',
    date: 'Date',
    dueDate: 'Due Date',
    approvalNo: 'Approval No.',
    billTo: 'Bill To',
    itemDescription: 'Item Description',
    category: 'Category',
    batchNo: 'Batch No.',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    total: 'Total',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    totalAmount: 'Total Amount',
    grandTotal: 'Grand Total',
    amountPaid: 'Amount Paid',
    balanceDue: 'Balance Due',
    paymentStatus: 'Payment Status',
    paid: 'Paid',
    partial: 'Partial',
    pending: 'Pending',
    unpaid: 'Unpaid',
    paymentTerms: 'Payment Terms',
    days: 'days',
    notes: 'Notes',
    thankYouForBusiness: 'Thank you for your business!',
    invoiceGeneratedOn: 'This invoice was generated on',
    forQuestionsContact: 'For any questions regarding this invoice, please contact us at',
    enterpriseResourcePlanningSystem: 'Enterprise Resource Planning System',
    businessDistrict: 'Business District',
    cairo: 'Cairo',
    egypt: 'Egypt',
    
    // Additional CreateQuotation keys
    termsConditions: 'Terms & Conditions',
    enterTermsConditions: 'Enter terms and conditions for this quotation...',
    termsWillAppearOnDocument: 'These terms will appear on the printed quotation document.',
    quotationSummary: 'Quotation Summary',
    quickActions: 'Quick Actions',
    previewQuotation: 'Preview Quotation',
    quotationPreview: 'Quotation Preview',
    reviewQuotationBeforeSending: 'Review your quotation before sending',
    quotation: 'Quotation',
    validUntil: 'Valid Until',
    noCustomerSelected: 'No customer selected',
    serviceType: 'Service Type',
    item: 'Item',
    uom: 'UoM',
    processing: 'Processing',
    grade: 'Grade',
    notesSpecialInstructions: 'Notes & Special Instructions',
    method: 'Method',
    fee: 'Fee',
    sendQuotation: 'Send Quotation',
    draftQuotations: 'Draft Quotations',
    manageDraftQuotations: 'Manage and continue working on your saved draft quotations',
    pleaseSelectCustomerToPreview: 'Please select a customer to preview the quotation',
    
    // User Management Module
    greenModulesAssignedPermissions: 'Green modules have been assigned permissions. Click "Add Permission" to assign access to unassigned modules.',
    tabControls: 'Tab Controls',
    contentVisibility: 'Content Visibility',
    userActions: 'User Actions',
    controlTabsVisibility: 'Control which tabs are visible in the module interface',
    manageContentDisplay: 'Manage what content and data is displayed to users',
    defineUserActions: 'Define what actions users can perform in this module',
    usersWillSeeTabs: 'Users will see these tabs in the module',
    contentWillBeVisible: 'This content will be visible to users',
    usersCanPerformActions: 'Users can perform these actions',
    moduleAccessDenied: 'Module access is denied',
    grantModuleAccessFirst: 'Grant module access first to configure individual features',
    permissionsSaved: 'Permissions saved',
    allPermissionChangesSaved: 'All permission changes have been saved successfully.',
    saveChanges: 'Save Changes',
    permissionsUpdated: 'Permissions updated',
    modulePermissionsConfigured: 'Module permissions have been configured successfully.',
    saveConfiguration: 'Save Configuration',
    cancel: 'Cancel',
    close: 'Close',
    permissionRemoved: 'Permission removed',
    permissionRemovedSuccessfully: 'The permission has been removed successfully.',
    error: 'Error',
    failedToDeletePermission: 'Failed to delete permission',
    managePermissions: 'Manage Permissions',
    manageModulePermissionsFor: 'Manage module permissions for',
    currentPermissions: 'Current Permissions',
    module: 'Module',
    access: 'Access',
    actions: 'Actions',
    granted: 'Granted',
    denied: 'Denied',
    configure: 'Configure',
    remove: 'Remove',
    noPermissionsAssigned: 'No permissions assigned yet',
    availableModules: 'Available Modules',
    fullAccessGranted: 'Full access granted',
    accessGrantedToAllModules: 'Access granted to all {{count}} ERP modules.',
    grantAllModules: 'Grant All Modules',
    modules: 'modules',
    configureModulePermissions: 'Configure Module Permissions',
    configureDetailedPermissionsFor: 'Configure detailed permissions for',
    moduleFor: 'module for',
    availableFeatures: 'Available Features',
    moduleAccessGranted: 'Module Access Granted',
    controlsVisibilityAndAccess: 'Controls visibility and access to this feature',
    of: 'of',
    featuresEnabled: 'features enabled',
    
    // Additional User Management translations
    userStatusUpdatedSuccessfully: 'User status updated successfully',
    userRoleUpdatedSuccessfully: 'User role updated successfully',
    failedToUpdateUserStatus: 'Failed to update user status',
    failedToUpdateUserRole: 'Failed to update user role',
    selectRole: 'Select Role',
    selectStatus: 'Select Status',
    admin: 'Admin',
    manager: 'Manager',
    staff: 'Staff',
    accountant: 'Accountant',
    inventoryManager: 'Inventory Manager',
    salesRep: 'Sales Rep',
    active: 'Active',
    inactive: 'Inactive',
    suspended: 'Suspended',
    creating: 'Creating...',
    create: 'Create',
    allModules: 'All Modules',
    systemUsers: 'System Users',
    user: 'User',
    permissions: 'Permissions',
    
    // OrderManagement translations
    selectCustomer: 'Select customer...',
    searchCustomers: 'Search customers...',
    noCustomerFound: 'No customer found.',
    batchNumber: 'Batch Number',
    autoGenerated: 'Auto-generated',
    finalProduct: 'Final Product',
    describeFinalProduct: 'Describe the final product',
    rawMaterials: 'Raw Materials',
    selectMaterial: 'Select material',
    quantity: 'Qty',
    unitPrice: 'Unit Price',
    packaging: 'Packaging',
    selectPackaging: 'Select packaging',
    additionalCosts: 'Additional Costs',
    transportationCost: 'Transportation Cost',
    laborCost: 'Labor Cost',
    equipmentCost: 'Equipment Cost',
    overheadCost: 'Overhead Cost',
    createProductionOrder: 'Create Production Order'
  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    products: 'المنتجات',
    inventory: 'المخزون',
    expenses: 'المصروفات',
    accounting: 'المحاسبة',
    suppliers: 'الموردين',
    customers: 'العملاء',
    createInvoice: 'إنشاء فاتورة',
    createQuotation: 'إنشاء عرض سعر',
    invoiceHistory: 'تاريخ الفواتير',
    quotationHistory: 'تاريخ عروض الأسعار',
    orderManagement: 'إدارة الطلبات',
    ordersHistory: 'تاريخ الطلبات',
    label: 'تسمية',
    reports: 'التقارير',
    procurement: 'المشتريات',
    userManagement: 'إدارة المستخدمين',
    systemPreferences: 'إعدادات النظام',
    logout: 'تسجيل الخروج',
    
    // Common
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    add: 'إضافة',
    search: 'بحث',
    filter: 'فلتر',
    export: 'تصدير',
    import: 'استيراد',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    warning: 'تحذير',
    
    // Profile & Settings
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    notifications: 'الإشعارات',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    
    // Financial
    totalAssets: 'إجمالي الأصول',
    totalLiabilities: 'إجمالي الخصوم',
    monthlyRevenue: 'الإيرادات الشهرية',
    monthlyExpenses: 'المصروفات الشهرية',
    
    // Company
    companyName: 'نظام إدارة موارد مورجان الكيميائية',
    
    // Inventory Management
    inventoryManagement: 'إدارة المخزون',
    addItem: 'إضافة عنصر',
    selectWarehouse: 'اختر المستودع',
    allWarehouses: 'جميع المستودعات',
    allStock: 'جميع المخزون',
    selectedWarehouse: 'المستودع المحدد',
    importCsv: 'استيراد CSV',
    exportCsv: 'تصدير CSV',
    createLabels: 'إنشاء ملصقات',
    inventorySettings: 'إعدادات المخزون',
    warehouseSelector: 'محدد المستودع',
    addWarehouse: 'إضافة مستودع',
    editWarehouse: 'تعديل المستودع',
    allStock: 'جميع المخزون',
    viewingInventory: 'عرض المخزون عبر',
    allWarehouses: 'جميع المستودعات',
    viewingInventoryFor: 'عرض المخزون لـ',
    inventoryModuleAr: 'المخزون',
    categories: 'الفئات',
    searchInventory: 'البحث في المخزون...',
    filterByStatus: 'فلتر حسب الحالة',
    filterByCategory: 'فلتر حسب الفئة',
    allStatuses: 'جميع الحالات',
    inStock: 'متوفر',
    outOfStock: 'نفد المخزون',
    expired: 'منتهي الصلاحية',
    allCategories: 'جميع الفئات',
    product: 'المنتج',
    category: 'الفئة',
    batchNo: 'رقم الدفعة',
    gs1Code: 'كود GS1',
    type: 'النوع',
    quantity: 'الكمية',
    description: 'الوصف',
    location: 'الموقع',
    shelf: 'الرف',
    price: 'السعر',
    expiryDate: 'تاريخ الانتهاء',
    actions: 'الإجراءات',
    createLabel: 'إنشاء ملصق',
    showHistory: 'عرض التاريخ',
    previous: 'السابق',
    next: 'التالي',
    page: 'صفحة',
    of: 'من',
    noProductsFound: 'لم يتم العثور على منتجات',
    tryAdjustingFilters: 'جرب تعديل المرشحات',
    addFirstProduct: 'أضف منتجك الأول للبدء',
    addProduct: 'إضافة منتج',
    
    // Dialog translations
    editProductInfo: 'تحرير معلومات المنتج',
    addNewProduct: 'إضافة منتج جديد',
    updateProductDetails: 'تحديث تفاصيل المنتج الشاملة ومعلومات المخزون',
    registerNewProduct: 'تسجيل منتج صيدلاني جديد بتفاصيل ومواصفات كاملة',
    productHistory: 'تاريخ المنتج والتحليلات',
    comprehensiveHistory: 'تاريخ شامل وتحليلات الأداء لـ',
    loadingProductDetails: 'جاري تحميل تفاصيل المنتج...',
    
    // Inventory Settings Dialog
    configureInventoryOptions: 'تكوين خيارات القوائم المنسدلة للمخزون',
    manageDropdownOptions: 'إدارة الخيارات المتاحة في وحدات القياس وأنواع المنتجات وخيارات الحالة وأنواع المواقع.',
    unitsOfMeasure: 'وحدات القياس',
    itemTypes: 'أنواع العناصر',
    statusOptions: 'خيارات الحالة',
    locationTypes: 'أنواع المواقع',
    newUnitPlaceholder: 'وحدة جديدة (مثل: مل، أقراص)',
    newItemTypePlaceholder: 'نوع عنصر جديد',
    newStatusPlaceholder: 'خيار حالة جديد',
    newLocationPlaceholder: 'نوع موقع جديد',
    done: 'تم',
    
    // Additional ProductForm translations
    drugName: 'اسم الدواء',
    chemicalName: 'الاسم الكيميائي',
    description: 'الوصف',
    unitOfMeasure: 'وحدة القياس',
    lowStockThreshold: 'حد المخزون المنخفض',
    costPrice: 'سعر التكلفة',
    sellingPrice: 'سعر البيع',
    warehouse: 'المستودع',
    shelfNumber: 'رقم الرف',
    status: 'الحالة',
    productType: 'نوع المنتج',
    
    // Form buttons
    saving: 'جاري الحفظ...',
    saveProduct: 'حفظ المنتج',
    updateProduct: 'تحديث المنتج',
    
    // Warehouse Dialogs
    editWarehouseDialogAr: 'تعديل المستودع',
    addNewWarehouse: 'إضافة مستودع جديد',
    updateWarehouseDetails: 'تحديث تفاصيل هذا المستودع',
    enterWarehouseDetails: 'أدخل تفاصيل المستودع الجديد',
    warehouseNameAr: 'الاسم',
    warehouseLocationAr: 'الموقع',
    warehouseNamePlaceholder: 'اسم المستودع',
    warehouseLocationPlaceholder: 'موقع المستودع',
    warehouseUpdated: 'تم تحديث المستودع',
    warehouseUpdatedSuccess: 'تم تحديث تفاصيل المستودع بنجاح.',
    warehouseAdded: 'تم إضافة المستودع',
    warehouseAddedSuccess: 'تم إضافة المستودع الجديد بنجاح.',
    saveChanges: 'حفظ التغييرات',
    addWarehouseBtnAr: 'إضافة مستودع',
    transferProductToWarehouse: 'نقل المنتج إلى مستودع آخر',
    transferStockDescription: 'نقل المخزون من المستودع الحالي إلى موقع مستودع مختلف',
    productDetails: 'تفاصيل المنتج',
    productNameAr: 'المنتج',
    currentStock: 'المخزون الحالي',
    currentWarehouse: 'المستودع الحالي',
    unknown: 'غير معروف',
    targetWarehouse: 'المستودع المستهدف',
    selectTargetWarehouse: 'اختر المستودع المستهدف',
    transferQuantity: 'كمية النقل',
    enterQuantityToTransfer: 'أدخل الكمية المراد نقلها',
    maximum: 'الحد الأقصى',
    transferNotesOptional: 'ملاحظات النقل (اختيارية)',
    addTransferNotes: 'أضف أي ملاحظات حول هذا النقل...',
    transferInitiated: 'تم بدء النقل',
    transferringProduct: 'نقل',
    from: 'من',
    to: 'إلى',
    confirmTransfer: 'تأكيد النقل',
    
    // Product History Dialog
    productInformation: 'معلومات المنتج',
    skuCode: 'رمز المنتج',
    manufacturer: 'الشركة المصنعة',
    inventoryDetails: 'تفاصيل المخزون',
    currentQuantity: 'الكمية الحالية',
    warehouseLocation: 'موقع المستودع',
    mainWarehouse: 'المستودع الرئيسي',
    reorderLevel: 'مستوى إعادة الطلب',
    stockValue: 'قيمة المخزون',
    lastStockMovement: 'آخر حركة مخزون',
    unitsReceived: 'وحدة تم استلامها في',
    averageMonthlyUsage: 'متوسط الاستخدام الشهري',
    month: 'شهر',
    pricingInformation: 'معلومات التسعير',
    profitMargin: 'هامش الربح',
    profitPerUnit: 'الربح لكل وحدة',
    lastPriceUpdate: 'آخر تحديث للسعر',
    priceTrend: 'اتجاه السعر',
    increasing: 'متزايد',
    complianceQuality: 'الامتثال والجودة',
    batchNumber: 'رقم الدفعة',
    qualityStatus: 'حالة الجودة',
    approved: 'موافق عليه',
    lastQualityCheck: 'آخر فحص جودة',
    regulatoryStatus: 'الحالة التنظيمية',
    edaApproved: 'معتمد من EDA - ترخيص',
    activityTimeline: 'الجدول الزمني للأنشطة',
    productInfoUpdated: 'تم تحديث معلومات المنتج',
    quantityChanged: 'تم تغيير الكمية من 150 إلى',
    updatedBy: 'محدث من: مدير النظام',
    stockReceived: 'تم استلام المخزون',
    receivedUnits: 'تم استلام',
    fromSupplier: 'من المورد',
    purchaseOrder: 'أمر الشراء',
    labelGenerated: 'تم إنشاء الملصق',
    productLabelCreated: 'تم إنشاء ملصق المنتج للدفعة',
    labelType: 'نوع الملصق: درجة صيدلانية',
    productAddedInventory: 'تم إضافة المنتج إلى المخزون',
    initialStock: 'المخزون الأولي',
    createdBy: 'تم إنشاؤه بواسطة: مدير المخزون',
    close: 'إغلاق',
    exportReport: 'تصدير التقرير',
    transferToWarehouse: 'نقل إلى المستودع',
    editProduct: 'تعديل المنتج',
    
    // Categories Management
    'Manage product categories used in inventory and sales': 'إدارة فئات المنتجات المستخدمة في المخزون والمبيعات',
    'No categories found': 'لم يتم العثور على فئات',
    'Add your first category below': 'أضف فئتك الأولى أدناه',
    'Name': 'الاسم',
    'Description': 'الوصف',
    'Category Name': 'اسم الفئة',
    'Description (optional)': 'الوصف (اختياري)',
    'Adding...': 'جاري الإضافة...',
    'Add Category': 'إضافة فئة',
    'Confirm Deletion': 'تأكيد الحذف',
    'Are you sure you want to delete the category': 'هل أنت متأكد من أنك تريد حذف الفئة',
    'This action cannot be undone': 'لا يمكن التراجع عن هذا الإجراء',
    'Cancel': 'إلغاء',
    'Deleting...': 'جاري الحذف...',
    'Delete': 'حذف',
    'manageCategories': 'إدارة الفئات',
    'more': 'المزيد',
    'categoriesDescription': 'انقر على "إدارة الفئات" لإضافة أو تعديل أو حذف فئات المنتجات',

    // Create Invoice
    createInvoiceArabic: 'إنشاء فاتورة',
    invoiceManagement: 'إدارة الفواتير',
    createNewInvoicesAndManageDrafts: 'إنشاء فواتير جديدة وإدارة المسودات',
    customerInfo: 'معلومات العميل',
    chooseCustomer: 'اختر العميل',
    customerName: 'اسم العميل',
    company: 'الشركة',
    emailInvoice: 'البريد الإلكتروني',
    phoneInvoice: 'الهاتف',
    sectorInvoice: 'القطاع',
    addressInvoice: 'العنوان',
    taxNumberInvoice: 'الرقم الضريبي',
    selectProduct: 'اختر المنتج',
    productName: 'اسم المنتج',
    unitPrice: 'سعر الوحدة',
    total: 'المجموع',
    addInvoiceItem: 'إضافة عنصر',
    removeItem: 'إزالة العنصر',
    paymentInfo: 'معلومات الدفع',
    paymentMethod: 'طريقة الدفع',
    generateInvoice: 'إنشاء الفاتورة',
    downloadPdf: 'تحميل PDF',
    cash: 'نقداً',
    visa: 'فيزا',
    cheque: 'شيك',
    bankTransfer: 'تحويل بنكي',
    
    // Dashboard
    welcomeToPremier: 'مرحبا بك في بريمير ERP',
    yourBusinessOverview: 'نظرة عامة على أعمالك',
    financialSummary: 'الملخص المالي',
    operationalMetrics: 'المقاييس التشغيلية',
    inventoryAlerts: 'تنبيهات المخزون',
    salesOverview: 'نظرة عامة على المبيعات',
    salesDistribution: 'توزيع المبيعات',
    categoryPerformance: 'أداء الفئات',
    totalRevenue: 'إجمالي الإيرادات',
    totalExpenses: 'إجمالي المصروفات',
    netProfit: 'صافي الربح',
    cashBalance: 'الرصيد النقدي',
    pendingOrders: 'الطلبات المعلقة',
    outstandingAR: 'المديونيات المستحقة',
    totalAccounts: 'إجمالي الحسابات',
    trialBalance: 'ميزان المراجعة',
    lowStockItems: 'عناصر المخزون المنخفض',
    expiringProducts: 'المنتجات المنتهية الصلاحية',
    warehouseBreakdown: 'توزيع المستودعات',
    viewDetails: 'عرض التفاصيل',
    
    // Expiring Products Card
    expired: 'منتهي الصلاحية',
    expiring: 'قارب على الانتهاء',
    expiresToday: 'ينتهي اليوم',
    expiresTomorrow: 'ينتهي غداً',
    daysLeft: '{days} يوم متبقي',
    noExpiry: 'لا يوجد تاريخ انتهاء',
    errorLoadingExpiryData: 'خطأ في تحميل بيانات الصلاحية',
    unableToLoadExpiry: 'غير قادر على تحميل معلومات الصلاحية. يرجى المحاولة مرة أخرى لاحقاً.',
    noProductsExpiringSoon: 'لا توجد منتجات قاربت على انتهاء الصلاحية!',
    stock: 'المخزون',
    showLess: 'عرض أقل',
    showAllItems: 'عرض جميع العناصر {count}',
    
    // Low Stock Card
    lowStockProducts: 'منتجات المخزون المنخفض',
    lowStockAlert: 'تنبيه المخزون المنخفض',
    errorLoadingStockData: 'خطأ في تحميل بيانات المخزون',
    unableToLoadStock: 'غير قادر على تحميل معلومات المخزون. يرجى المحاولة مرة أخرى لاحقاً.',
    outOfStock: 'نفذ',
    low: 'منخفض',
    allProductsWellStocked: 'جميع المنتجات بمخزون جيد!',
    reorder: 'إعادة الطلب',
    
    // Dashboard Chart Dialogs
    salesOverviewEnhanced: 'نظرة عامة على المبيعات - عرض محسّن',
    salesAnalytics: 'تحليلات المبيعات',
    peakMonth: 'شهر الذروة',
    december: 'ديسمبر',
    sales: 'المبيعات',
    growthRate: 'معدل النمو',
    yoy: 'سنة بعد سنة',
    trendingUp: 'في تصاعد',
    average: 'المتوسط',
    monthly: 'شهري',
    targetMet: 'تم تحقيق الهدف',
    thisYear: 'هذا العام',
    target: 'الهدف',
    salesDistributionEnhanced: 'توزيع المبيعات - عرض محسّن',
    distributionDetails: 'تفاصيل التوزيع',
    categoryPerformanceEnhanced: 'أداء الفئات - عرض محسّن',
    performanceMetrics: 'مقاييس الأداء',
    vsLastMonth: 'مقارنة بالشهر الماضي',
    
    // Accounting Module
    accountingDashboard: 'لوحة المحاسبة',
    chartOfAccounts: 'دليل الحسابات',
    journalEntries: 'القيود اليومية',
    customerPayments: 'مدفوعات العملاء',
    profitAndLoss: 'الأرباح والخسائر',
    balanceSheet: 'الميزانية العمومية',
    trialBalanceReport: 'تقرير ميزان المراجعة',
    accountingPeriods: 'الفترات المحاسبية',
    financialIntegration: 'التكامل المالي',
    
    // Expenses Module
    expenseManagement: 'إدارة المصروفات',
    addExpense: 'إضافة مصروف',
    expenseCategory: 'فئة المصروف',
    expenseAmount: 'المبلغ',
    expenseDate: 'التاريخ',
    expenseDescription: 'الوصف',
    paymentMethodExpense: 'طريقة الدفع',
    costCenter: 'مركز التكلفة',
    receiptUpload: 'رفع الإيصال',
    expenseStatus: 'حالة المصروف',
    
    // Reports Module
    reportsAnalytics: 'التقارير والتحليلات',
    inventoryReports: 'تقارير المخزون',
    salesReports: 'تقارير المبيعات',
    financialReports: 'التقارير المالية',
    customerReports: 'تقارير العملاء',
    supplierReports: 'تقارير الموردين',
    exportReport: 'تصدير التقرير',
    generateReport: 'إنشاء التقرير',
    reportPeriod: 'فترة التقرير',
    
    // Procurement Module
    procurementManagement: 'إدارة المشتريات',
    createPurchaseOrder: 'إنشاء أمر شراء',
    purchaseOrderHistory: 'تاريخ أوامر الشراء',
    selectSupplier: 'اختر المورد',
    expectedDelivery: 'التسليم المتوقع',
    procurementStatus: 'حالة المشتريات',
    approvalRequired: 'يتطلب الموافقة',
    
    // Order Management
    orderManagementSystem: 'نظام إدارة الطلبات',
    newOrder: 'طلب جديد',
    orderStatus: 'حالة الطلب',
    orderNumber: 'رقم الطلب',
    orderDate: 'تاريخ الطلب',
    deliveryDate: 'تاريخ التسليم',
    orderTotal: 'إجمالي الطلب',
    
    // User Management
    userManagementSystem: 'نظام إدارة المستخدمين',
    addUser: 'إضافة مستخدم',
    userName: 'اسم المستخدم',
    userEmail: 'البريد الإلكتروني',
    userRole: 'دور المستخدم',
    userStatus: 'حالة المستخدم',
    userPermissions: 'صلاحيات المستخدم',
    lastLogin: 'آخر دخول',
    manageSystemUsers: 'إدارة مستخدمي النظام وصلاحياتهم',
    createUser: 'إنشاء مستخدم',
    createNewUser: 'إنشاء مستخدم جديد',
    username: 'اسم المستخدم',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    role: 'الدور',
    status: 'الحالة',
    enterUsername: 'أدخل اسم المستخدم',
    enterFullName: 'أدخل الاسم الكامل',
    enterEmail: 'أدخل البريد الإلكتروني',
    enterPassword: 'أدخل كلمة المرور',
    selectRole: 'اختر الدور',
    selectStatus: 'اختر الحالة',
    admin: 'مدير',
    manager: 'مدير',
    staff: 'موظف',
    accountant: 'محاسب',
    inventoryManager: 'مدير المخزون',
    salesRep: 'مندوب مبيعات',
    suspended: 'موقوف',
    systemUsers: 'مستخدمو النظام',
    user: 'المستخدم',
    permissions: 'الصلاحيات',
    allModules: 'جميع الوحدات',
    modules: 'الوحدات',
    managePermissions: 'إدارة الصلاحيات',
    grantAllPermissions: 'منح جميع الصلاحيات',
    revokeAllPermissions: 'إلغاء جميع الصلاحيات',
    granted: 'ممنوحة',
    denied: 'مرفوضة',
    adminAccess: 'وصول المدير',
    userCreatedSuccessfully: 'تم إنشاء المستخدم بنجاح',
    userDeletedSuccessfully: 'تم حذف المستخدم بنجاح',
    failedToCreateUser: 'فشل في إنشاء المستخدم',
    failedToDeleteUser: 'فشل في حذف المستخدم',
    permissionUpdatedSuccessfully: 'تم تحديث الصلاحية بنجاح',
    permissionRemovedSuccessfully: 'تم إزالة الصلاحية بنجاح',
    failedToUpdatePermission: 'فشل في تحديث الصلاحية',
    failedToRemovePermission: 'فشل في إزالة الصلاحية',
    cannotDeleteYourself: 'لا يمكن حذف حسابك الخاص',
    creating: 'جاري الإنشاء...',
    create: 'إنشاء',
    accessDenied: 'الوصول مرفوض',
    noPermissionForModule: 'ليس لديك صلاحية للوصول إلى هذه الوحدة',
    contactAdminForAccess: 'اتصل بالمدير للحصول على الوصول',
    
    // System Preferences
    systemPreferencesTitle: 'إعدادات النظام',
    companySettings: 'إعدادات الشركة',
    currencySettings: 'إعدادات العملة',
    taxSettings: 'إعدادات الضرائب',
    notificationSettings: 'إعدادات الإشعارات',
    backupSettings: 'إعدادات النسخ الاحتياطي',
    securitySettings: 'إعدادات الأمان',
    
    // Common Actions
    view: 'عرض',
    update: 'تحديث',
    deleteAction: 'حذف',
    confirm: 'تأكيد',
    cancelAction: 'إلغاء',
    discardChanges: 'تجاهل التغييرات',
    refresh: 'تحديث',
    print: 'طباعة',
    download: 'تحميل',
    upload: 'رفع',
    
    // Status Messages
    successMessage: 'تمت العملية بنجاح',
    errorMessage: 'حدث خطأ',
    loadingMessage: 'جاري التحميل...',
    savingMessage: 'جاري الحفظ...',
    deletingMessage: 'جاري الحذف...',
    noDataFound: 'لا توجد بيانات',
    
    // Time periods
    today: 'اليوم',
    yesterday: 'أمس',
    thisWeek: 'هذا الأسبوع',
    lastWeek: 'الأسبوع الماضي',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    lastYear: 'السنة الماضية',
    customRange: 'نطاق مخصص',
    
    // Dashboard additions
    currentMonthRevenue: 'إيرادات الشهر الحالي',
    revenueMinusExpenses: 'الإيرادات بعد خصم المصروفات',
    pendingInvoices: 'فواتير معلقة',
    ordersPending: 'طلبات معلقة',
    expenseEntries: 'إدخالات المصروفات',
    availableCashFlow: 'التدفق النقدي المتاح',
    paymentsReceived: 'المدفوعات المستلمة',
    thisMonthPayments: 'مدفوعات هذا الشهر',
    inventoryValue: 'قيمة المخزون',
    costValue: 'قيمة التكلفة',
    selling: 'البيع',
    warehouses: 'مستودعات',
    newThisMonth: 'جديد هذا الشهر',
    fromLastMonth: 'من الشهر الماضي',
    calculatingTrends: 'حساب الاتجاهات...',
    todaySales: 'مبيعات اليوم',
    daily: 'يومي',
    monthSales: 'مبيعات الشهر',
    collectedTax: 'الضريبة المحصلة',
    vatCollectedFromSales: 'ضريبة القيمة المضافة المحصلة من المبيعات',
    inventoryValueBreakdown: 'تفصيل قيمة المخزون',
    realTimeWarehouseAnalysis: 'تحليل المستودعات في الوقت الفعلي',
    loadingWarehouseBreakdown: 'جاري تحميل تفاصيل المستودعات',
    totalCostValue: 'إجمالي قيمة التكلفة',
    totalSellingValue: 'إجمالي قيمة البيع',
    totalQuantity: 'الكمية الإجمالية',
    units: 'وحدات',
    sellingValue: 'قيمة البيع',
    avgUnitCost: 'متوسط تكلفة الوحدة',
    
    // OrdersHistory page
    productionAndRefiningOrderTracking: 'تتبع طلبات الإنتاج والتكرير',
    totalOrders: 'إجمالي الطلبات',
    activeProductionOrders: 'طلبات الإنتاج النشطة',
    totalRevenue: 'إجمالي الإيرادات',
    fromCompletedOrders: 'من الطلبات المكتملة',
    totalCosts: 'إجمالي التكاليف',
    productionExpenses: 'مصروفات الإنتاج',
    netProfit: 'صافي الربح',
    margin: 'الهامش',
    noData: 'لا توجد بيانات',
    filtersAndSearch: 'الفلاتر والبحث',
    searchOrders: 'البحث في الطلبات...',
    filterByStatus: 'فلتر حسب الحالة',
    allStatuses: 'جميع الحالات',
    completed: 'مكتمل',
    inProgress: 'قيد التقدم',
    cancelled: 'ملغي',
    filterByType: 'فلتر حسب النوع',
    allTypes: 'جميع الأنواع',
    production: 'إنتاج',
    manufacturing: 'تصنيع',
    refining: 'تكرير',
    exportCSV: 'تصدير CSV',
    loadingOrderHistory: 'جاري تحميل تاريخ الطلبات...',
    orderHistory: 'تاريخ الطلبات',
    orders: 'طلبات',
    orderNumber: 'رقم الطلب',
    batchNumber: 'رقم الدفعة',
    type: 'النوع',
    customer: 'العميل',
    product: 'المنتج',
    status: 'الحالة',
    revenue: 'الإيرادات',
    profit: 'الربح',
    actions: 'الإجراءات',
    viewDetails: 'عرض التفاصيل',
    downloadReport: 'تحميل التقرير',
    orderDetails: 'تفاصيل الطلب',
    completeInformationForBatch: 'معلومات كاملة للدفعة',
    orderInformation: 'معلومات الطلب',
    targetProduct: 'المنتج المستهدف',
    customerInformation: 'معلومات العميل',
    customerName: 'اسم العميل',
    company: 'الشركة',
    timeline: 'الجدول الزمني',
    orderDate: 'تاريخ الطلب',
    completionDate: 'تاريخ الإنجاز',
    financialSummary: 'الملخص المالي',
    totalCost: 'إجمالي التكلفة',
    profitMargin: 'هامش الربح',
    additionalCosts: 'التكاليف الإضافية',
    transportation: 'النقل',
    labor: 'العمالة',
    equipment: 'المعدات',
    qualityControl: 'مراقبة الجودة',
    storage: 'التخزين',
    totalAdditional: 'إجمالي الإضافي',
    rawMaterialsUsed: 'المواد الخام المستخدمة',
    exportReport: 'تصدير التقرير',
    exportAsPDF: 'تصدير كـ PDF',
    exportAsExcel: 'تصدير كـ Excel',
    printReport: 'طباعة التقرير',
    generateInvoice: 'إنشاء فاتورة',
    showing: 'عرض',
    to: 'إلى',
    of: 'من',
    orders: 'طلبات',
    previous: 'السابق',
    next: 'التالي',
    
    // Login page
    signInToAccount: 'تسجيل الدخول إلى حسابك',
    welcomeBack: 'مرحبًا بعودتك',
    signInPrompt: 'تسجيل الدخول إلى نظام Premier ERP',
    email: 'البريد الإلكتروني',
    enterEmail: 'أدخل بريدك الإلكتروني',
    password: 'كلمة المرور',
    enterPassword: 'أدخل كلمة المرور',
    signIn: 'تسجيل الدخول',
    secureERPSystem: 'نظام Premier ERP الآمن',
    enterpriseSecurity: 'أمن المؤسسات',
    termsAndPrivacy: 'بتسجيل الدخول، فإنك توافق على شروط الخدمة وسياسة الخصوصية',
    
    // Customer Management
    customerRecords: 'سجلات العملاء',
    allCustomers: 'جميع العملاء',
    activeCustomers: 'العملاء النشطون',
    inactiveCustomers: 'العملاء غير النشطين',
    viewProfile: 'عرض الملف الشخصي',
    viewOrders: 'عرض الطلبات',
    editCustomer: 'تعديل العميل',
    deleteCustomer: 'حذف العميل',
    customerDeleted: 'تم حذف العميل بنجاح',
    importCustomers: 'استيراد العملاء',
    exportCustomers: 'تصدير العملاء',
    addCustomer: 'إضافة عميل',
    searchCustomers: 'البحث عن العملاء بالاسم أو البريد الإلكتروني أو الهاتف',
    filterByStatus: 'فلتر حسب الحالة',
    showingResults: 'عرض النتائج',
    noCustomersFound: 'لم يتم العثور على عملاء',
    tryDifferentSearch: 'حاول تعديل معايير البحث',
    loadingCustomers: 'جاري تحميل العملاء...',
    
    // Customer Analytics
    reportsAnalytics: 'التقارير والتحليلات',
    totalCustomers: 'إجمالي العملاء',
    active: 'نشط',
    newThisMonth: 'جدد هذا الشهر',
    avgOrderValue: 'متوسط قيمة الطلب',
    perCustomer: 'لكل عميل',
    repeatCustomers: 'العملاء المتكررون',
    retentionRate: 'معدل الاحتفاظ',
    customerDistributionBySector: 'توزيع العملاء حسب القطاع',
    topCustomersByRevenue: 'أفضل العملاء حسب الإيرادات',
    geographicDistribution: 'التوزيع الجغرافي',
    customers: 'عملاء',
    
    // Additional Customer Page translations
    customerManagement: 'إدارة العملاء',
    manageClients: 'إدارة العملاء',
    activeSectors: 'القطاعات النشطة',
    industryTypes: 'أنواع الصناعات',
    customerValue: 'قيمة العملاء',
    totalPortfolio: 'المحفظة الإجمالية',
    recentAdditions: 'الإضافات الأخيرة',
    topSector: 'القطاع الأعلى',
    geographicSpread: 'الانتشار الجغرافي',
    cities: 'مدن',
    coverageArea: 'منطقة التغطية',
    monthlyIncrease: 'الزيادة الشهرية',
    errorLoadingCustomers: 'خطأ في تحميل العملاء',
    pleaseTryAgainLater: 'يرجى المحاولة مرة أخرى لاحقاً',
    noMatchingCustomersFound: 'لم يتم العثور على عملاء مطابقين',
    tryAdjustingSearchQuery: 'حاول تعديل استعلام البحث',
    noCustomersAvailable: 'لا يوجد عملاء متاحون',
    action: 'الإجراء',
    customerReportsAnalytics: 'تقارير وتحليلات العملاء',
    comprehensiveReportsInsights: 'تقارير ورؤى شاملة',
    exportPDF: 'تصدير PDF',
    loadingReports: 'جاري تحميل التقارير...',
    customerRevenue: 'إيرادات العملاء',
    monthlyGrowthTrend: 'اتجاه النمو الشهري',
    activeAccounts: 'الحسابات النشطة',
    
    // Add Customer Dialog
    addNewCustomer: 'إضافة عميل جديد',
    createComprehensiveCustomerDetails: 'إنشاء تفاصيل شاملة للعميل ومعلومات العلاقة التجارية',
    customerNameRequired: 'اسم العميل *',
    fullCustomerName: 'اسم العميل الكامل',
    positionTitle: 'المنصب/اللقب',
    jobTitlePosition: 'المسمى الوظيفي أو المنصب',
    customerStatus: 'حالة العميل',
    activeCustomer: 'عميل نشط',
    inactiveCustomer: 'عميل غير نشط',
    prospect: 'عميل محتمل',
    vipCustomer: 'عميل VIP',
    companyInformation: 'معلومات الشركة',
    fullCompanyName: 'اسم الشركة الكامل',
    industrySector: 'القطاع الصناعي',
    selectIndustrySector: 'اختر القطاع الصناعي',
    contactInformation: 'معلومات الاتصال',
    phoneNumber: 'رقم الهاتف',
    emailAddress: 'البريد الإلكتروني',
    addressTaxInformation: 'العنوان والمعلومات الضريبية',
    completeAddress: 'العنوان الكامل',
    customerAddress: 'عنوان العميل',
    taxNumberEta: 'الرقم الضريبي (تسجيل هيئة الضرائب)',
    enterTaxNumber: 'أدخل رقم تسجيل هيئة الضرائب المصرية',
    requiredForEta: 'مطلوب لظهور الفواتير في بوابة هيئة الضرائب الخاصة بالعميل',
    
    // Create Invoice page
    draftInvoices: 'مسودات الفواتير',
    createNewInvoice: 'إنشاء فاتورة جديدة',
    createInvoiceDescription: 'إنشاء فاتورة جديدة عن طريق اختيار عميل وإضافة منتجات',
    saveAsDraft: 'حفظ كمسودة',
    previewInvoice: 'معاينة الفاتورة',
    invoicesInProgress: 'الفواتير قيد العمل',
    resetToInvoice1: 'إعادة تعيين إلى الفاتورة 1',
    newInvoice: 'فاتورة جديدة',
    invoiceProgressAutoSaved: 'يتم حفظ تقدم الفاتورة تلقائيًا. يمكنك العمل على ما يصل إلى 4 فواتير في نفس الوقت.',
    nextInvoiceNumber: 'رقم الفاتورة التالي',
    customerInformation: 'معلومات العميل',
    selectOrCreateCustomer: 'اختر عميلاً موجودًا أو أنشئ عميلاً جديدًا',
    customer: 'العميل',
    selectCustomer: 'اختر عميل...',
    searchCustomer: 'البحث عن عميل...',
    noCustomersFoundFor: 'لم يتم العثور على عملاء لـ',
    createNewCustomer: 'إنشاء عميل جديد',
    typeToSearchCustomers: 'اكتب للبحث عن العملاء...',
    paperInvoiceNumber: 'رقم الفاتورة الورقية',
    paperInvoiceNumberPlaceholder: 'P-2025001',
    physicalInvoiceReference: 'رقم مرجع الفاتورة الفعلية لحفظ السجلات',
    approvalNumber: 'رقم الموافقة',
    approvalNumberPlaceholder: 'APP-2025001',
    internalApprovalReference: 'رقم مرجع الموافقة الداخلية',
    code: 'الكود',
    mobile: 'الجوال',
    etaNumber: 'رقم ETA',
    sector: 'القطاع',
    email: 'البريد الإلكتروني',
    address: 'العنوان',
    emailPlaceholder: 'customer@example.com',
    addressPlaceholder: 'عنوان العميل',
    draftSaved: 'تم حفظ المسودة',
    invoiceSavedAsDraft: 'تم حفظ الفاتورة كمسودة بنجاح',
    newCustomer: 'عميل جديد',
    companyName: 'اسم الشركة',
    companyNamePlaceholder: 'اسم الشركة',
    name: 'الاسم',
    customerNamePlaceholder: 'اسم العميل',
    position: 'المنصب',
    jobTitlePositionPlaceholder: 'المسمى الوظيفي/المنصب',
    phone: 'الهاتف',
    phoneNumberPlaceholder: 'رقم الهاتف',
    businessSectorPlaceholder: 'قطاع الأعمال',
    taxNumberEtaRegistration: 'الرقم الضريبي (تسجيل ETA)',
    egyptianTaxAuthorityPlaceholder: 'رقم تسجيل مصلحة الضرائب المصرية',
    requiredForEtaPortal: 'مطلوب لظهور الفواتير في بوابة ETA الخاصة بالعميل',
    customerEmailPlaceholder: 'customer@example.com',
    customerAddressPlaceholder: 'عنوان العميل',
    saveCustomer: 'حفظ العميل',
    invoiceItems: 'بنود الفاتورة',
    addProductsToInvoice: 'أضف منتجات إلى هذه الفاتورة',
    addItem: 'إضافة بند',
    selectFromQuotations: 'اختر من عروض الأسعار',
    selectFromOrderHistory: 'اختر من سجل الطلبات',
    printPreview: 'معاينة الطباعة',
    product: 'المنتج',
    category: 'الفئة',
    batchNo: 'رقم الدفعة',
    gs1Code: 'كود GS1',
    type: 'النوع',
    quantity: 'الكمية',
    unitPrice: 'سعر الوحدة',
    total: 'المجموع',
    action: 'الإجراء',
    selectProduct: 'اختر منتج...',
    searchProducts: 'البحث عن المنتجات...',
    noProductsFound: 'لم يتم العثور على منتجات',
    products: 'المنتجات',
    noCategory: 'بدون فئة',
    noSku: 'بدون رمز',
    noBarcode: 'بدون باركود',
    noItemsAdded: 'لم يتم إضافة بنود. انقر فوق "إضافة بند" لإضافة منتجات إلى هذه الفاتورة.',
    addAnotherItem: 'إضافة بند آخر',
    paymentDetails: 'تفاصيل الدفع',
    paymentStatus: 'حالة الدفع',
    selectPaymentStatus: 'اختر حالة الدفع',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    partialPayment: 'دفعة جزئية',
    paymentMethod: 'طريقة الدفع',
    selectPaymentMethod: 'اختر طريقة الدفع',
    cash: 'نقدي',
    visa: 'فيزا',
    cheque: 'شيك',
    bankTransfer: 'حوالة بنكية',
    uploadDocument: 'رفع مستند {type}',
    paymentTermsDays: 'شروط الدفع (بالأيام)',
    selectPaymentTerms: 'اختر شروط الدفع',
    dueImmediately: 'مستحق فوراً (0 يوم)',
    net7: 'صافي 7 (7 أيام)',
    net15: 'صافي 15 (15 يوم)',
    net30: 'صافي 30 (30 يوم)',
    net60: 'صافي 60 (60 يوم)',
    amountPaid: 'المبلغ المدفوع',
    orderSummary: 'ملخص الطلب',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    none: 'لا يوجد',
    percentage: 'نسبة مئوية',
    amount: 'مبلغ',
    discountAmount: 'مبلغ الخصم',
    subtotalAfterDiscount: 'المجموع الفرعي بعد الخصم',
    taxRate: 'معدل الضريبة (%)',
    taxAmount: 'مبلغ الضريبة',
    vat: 'ضريبة القيمة المضافة',
    vatRate: 'معدل ضريبة القيمة المضافة (%)',
    vatAmount: 'مبلغ ضريبة القيمة المضافة',
    grandTotal: 'الإجمالي الكلي',
    additionalNotes: 'أضف أي ملاحظات أو شروط إضافية...',
    createInvoiceButton: 'إنشاء فاتورة',
    invoiceCreated: 'تم إنشاء الفاتورة',
    invoiceCreatedSuccessfully: 'تم إنشاء الفاتورة بنجاح.',
    whatWouldYouLikeToDoNext: 'ماذا تريد أن تفعل بعد ذلك؟',
    viewAllInvoices: 'عرض جميع الفواتير',
    createAnotherInvoice: 'إنشاء فاتورة أخرى',
    
    // Draft Invoices
    draftInvoices: 'مسودات الفواتير',
    manageYourSavedInvoiceDrafts: 'إدارة مسودات الفواتير المحفوظة',
    clearAllDrafts: 'مسح جميع المسودات',
    allDraftsCleared: 'تم مسح جميع المسودات',
    allInvoiceDraftsHaveBeenDeleted: 'تم حذف جميع مسودات الفواتير',
    noDraftInvoices: 'لا توجد مسودات فواتير',
    youHaventSavedAnyInvoiceDrafts: 'لم تحفظ أي مسودات فواتير بعد. قم بإنشاء فاتورة واستخدم "حفظ كمسودة" لرؤيتها هنا.',
    invoiceFor: 'فاتورة لـ',
    untitledInvoiceDraft: 'مسودة فاتورة بدون عنوان',
    draft: 'مسودة',
    noCustomerSelected: 'لم يتم تحديد عميل',
    saved: 'محفوظ',
    items: 'عناصر',
    loadDraft: 'تحميل المسودة',
    deleteDraft: 'حذف المسودة',
    draftDeleted: 'تم حذف المسودة',
    invoiceDraftDeleted: 'تم حذف مسودة الفاتورة',
    draftLoaded: 'تم تحميل المسودة',
    invoiceDraftLoaded: 'تم تحميل مسودة الفاتورة',
    
    // Quotation Selector
    selectFromQuotations: 'اختر من عروض الأسعار',
    chooseQuotationToImport: 'اختر عرض سعر لاستيراد عناصره ومعلومات العميل إلى هذه الفاتورة',
    noQuotationsFound: 'لا توجد عروض أسعار',
    noQuotationsAvailable: 'لا توجد عروض أسعار متاحة للاستيراد منها.',
    approved: 'معتمد',
    pending: 'معلق',
    rejected: 'مرفوض',
    noCustomer: 'لا يوجد عميل',
    validUntil: 'صالح حتى',
    quotationImported: 'تم استيراد عرض السعر',
    quotationImportedSuccessfully: 'تم استيراد عرض السعر بنجاح',
    importAction: 'استيراد',
    
    // Order Selector
    selectFromOrderHistoryMenu: 'اختر من سجل الطلبات',
    chooseCompletedOrder: 'اختر طلبًا مكتملاً لاستيراد تفاصيله إلى هذه الفاتورة',
    noOrdersFound: 'لا توجد طلبات',
    noCompletedOrdersAvailable: 'لا توجد طلبات مكتملة متاحة للاستيراد منها.',
    completed: 'مكتمل',
    'in-progress': 'قيد التنفيذ',
    orderImported: 'تم استيراد الطلب',
    orderImportedSuccessfully: 'تم استيراد الطلب بنجاح',
    requestedQuantity: 'الكمية المطلوبة',
    completedOn: 'اكتمل في',
    batch: 'الدفعة',
    revenue: 'الإيرادات',
    
    // Invoice Preview Dialog
    invoicePreview: 'معاينة الفاتورة',
    downloadPDF: 'تحميل PDF',
    generating: 'جاري الإنشاء...',
    previewInvoiceBeforePrinting: 'معاينة الفاتورة قبل الطباعة أو التحميل',
    closePreview: 'إغلاق المعاينة',
    previewBeforePrinting: 'معاينة قبل الطباعة',
    invoice: 'فاتورة',
    invoiceNumber: 'رقم الفاتورة',
    date: 'التاريخ',
    dueDate: 'تاريخ الاستحقاق',
    approvalNo: 'رقم الموافقة',
    billTo: 'فاتورة إلى',
    noCustomerChosen: 'لم يتم اختيار عميل',
    itemDescription: 'وصف الصنف',
    qty: 'الكمية',
    netDays: 'صافي {days} أيام',
    enterpriseResourcePlanningSystem: 'نظام تخطيط موارد المؤسسات',
    businessDistrict: 'منطقة الأعمال',
    cairo: 'القاهرة',
    egypt: 'مصر',
    info: 'معلومات',
    totalAmount: 'المبلغ الإجمالي',
    thankYouForBusiness: 'شكراً لتعاملكم معنا!',
    partial: 'جزئي',
    pendingStatus: 'معلق',
    days: 'أيام',
    invoiceGeneratedOn: 'تم إنشاء هذه الفاتورة في',
    forQuestionsContact: 'لأية استفسارات بخصوص هذه الفاتورة، يرجى الاتصال بنا على',
    
    // Create Quotation Section
    generateProfessionalQuotations: 'إنشاء عروض أسعار احترافية لخدماتك الصيدلانية',
    preview: 'معاينة',
    saveDraft: 'حفظ كمسودة',
    sendQuotation: 'إرسال عرض السعر',
    createNew: 'إنشاء جديد',
    draftQuotations: 'مسودات عروض الأسعار',
    quotationType: 'نوع عرض السعر',
    selectTypeOfService: 'اختر نوع الخدمة التي تقدم عرض سعر لها',
    manufacturing: 'تصنيع',
    refining: 'تكرير',
    finished: 'منتج نهائي',
    pharmaceuticalManufacturing: 'تصنيع صيدلاني',
    chemicalRefining: 'تكرير كيميائي',
    finishedProducts: 'منتجات نهائية',
    customerDetails: 'العميل والتفاصيل',
    customerInfo: 'العميل',
    selectACustomer: 'اختر عميل',
    quotationNumber: 'رقم عرض السعر',
    serviceType: 'النوع',
    notesAndSpecialInstructions: 'ملاحظات وتعليمات خاصة',
    addSpecialNotes: 'أضف أي ملاحظات خاصة أو تعليمات لعرض السعر هذا...',
    addItems: 'إضافة عناصر',
    addItemsToQuotation: 'أضف عناصر {type} إلى عرض السعر',
    productService: 'المنتج/الخدمة',
    selectItem: 'اختر عنصر {type}',
    additionalDescription: 'وصف إضافي...',
    enterQuantity: 'أدخل الكمية',
    unitOfMeasurement: 'وحدة القياس',
    kilograms: 'كيلوجرام (كجم)',
    liters: 'لتر (ل)',
    tablets: 'أقراص',
    capsules: 'كبسولات',
    bottles: 'زجاجات',
    tubes: 'أنابيب',
    kits: 'مجموعات',
    unitsCount: 'وحدات',
    unitPriceQuotation: 'سعر الوحدة ($)',
    addItemToQuotation: 'إضافة عنصر إلى عرض السعر',
    processingTime: 'وقت المعالجة (أيام)',
    enterProcessingDays: 'أدخل أيام المعالجة',
    qualityGrade: 'درجة الجودة',
    pharmaceuticalGrade: 'درجة صيدلانية',
    foodGrade: 'درجة غذائية',
    industrialGrade: 'درجة صناعية',
    researchGrade: 'درجة بحثية',
    specificationsRequirements: 'المواصفات والمتطلبات',
    specifyPurityRequirements: 'حدد متطلبات النقاء، شروط المعالجة، معايير الجودة...',
    quotationItems: 'عناصر عرض السعر',
    itemsAdded: '{count} عنصر مضاف',
    processing: 'المعالجة',
    grade: 'الدرجة',
    specs: 'المواصفات',
    transportationDelivery: 'النقل والتوصيل',
    addShippingHandling: 'إضافة تكاليف الشحن والمناولة للنقل الصيدلاني',
    transportationType: 'نوع النقل',
    selectTransportationMethod: 'اختر طريقة النقل',
    standardDelivery: 'توصيل عادي (3-5 أيام)',
    expressDelivery: 'توصيل سريع (1-2 يوم)',
    coldChainTransport: 'نقل بالسلسلة الباردة (تحكم في درجة الحرارة)',
    hazardousMaterialsTransport: 'نقل المواد الخطرة',
    internationalShipping: 'شحن دولي',
    customerPickup: 'استلام العميل (بدون رسوم)',
    customTransportation: 'نقل مخصص',
    transportationFees: 'رسوم النقل ($)',
    transportationNotes: 'ملاحظات النقل',
    specialHandlingRequirements: 'متطلبات المناولة الخاصة، تعليمات التسليم، احتياجات التأمين...',
    transportationDetails: 'تفاصيل النقل:',
    standardDeliveryDetails: 'توصيل عادي مع التعبئة الأساسية والنقل العادي',
    expressDeliveryDetails: 'توصيل ذو أولوية مع معالجة وشحن معجل',
    coldChainDetails: 'نقل بدرجة حرارة محكومة (2-8 درجة مئوية) مع المراقبة',
    hazmatDetails: 'نقل متخصص للمواد الصيدلانية الخطرة',
    internationalDetails: 'الشحن الدولي مع التخليص الجمركي والوثائق',
    customDetails: 'ترتيب نقل مخصص حسب المتطلبات المحددة',
    taxConfiguration: 'إعدادات الضريبة',
    configureVAT: 'تكوين نسبة ضريبة القيمة المضافة لعرض السعر هذا',
    vatPercentage: 'نسبة ضريبة القيمة المضافة (%)',
    standardEgyptianVAT: 'ضريبة القيمة المضافة المصرية القياسية هي 14%. عدّل حسب الحاجة للمنتجات أو اللوائح المحددة.',
    termsConditions: 'الشروط والأحكام',
    standardTermsConditions: 'الشروط والأحكام القياسية لعروض الأسعار الصيدلانية',
    enterTermsConditions: 'أدخل الشروط والأحكام لعرض السعر هذا...',
    termsWillAppear: 'ستظهر هذه الشروط في مستند عرض السعر المطبوع.',
    quotationSummary: 'ملخص عرض السعر',
    transportation: 'النقل',
    vat: 'ضريبة القيمة المضافة',
    quickActions: 'إجراءات سريعة',
    createQuotationButton: 'إنشاء عرض السعر',
    previewQuotation: 'معاينة عرض السعر',
    quotationPreview: 'معاينة عرض السعر',
    reviewBeforeSending: 'مراجعة عرض السعر قبل الإرسال',
    quotation: 'عرض سعر',
    serviceTypeMenu: 'نوع الخدمة',
    manageAndContinue: 'إدارة ومواصلة العمل على مسودات عروض الأسعار المحفوظة',
    lastModified: 'آخر تعديل',
    ago: 'منذ',
    hours: 'ساعات',
    openingEditor: 'فتح المحرر',
    loadingForEditing: 'جاري تحميل {id} للتعديل...',
    previewLoading: 'تحميل المعاينة',
    preparingQuotationPreview: 'جاري تحضير معاينة عرض السعر...',
    sendingViaWhatsApp: 'الإرسال عبر واتساب',
    openingWhatsAppWithQuotation: 'فتح واتساب مع عرض السعر {id}...',
    
    // Additional CreateQuotation keys
    termsWillAppearOnDocument: 'ستظهر هذه الشروط في مستند عرض السعر المطبوع.',
    reviewQuotationBeforeSending: 'مراجعة عرض السعر قبل الإرسال',
    validUntilDate: 'صالح حتى',
    quotationItem: 'العنصر',
    notesSpecialInstructions: 'ملاحظات وتعليمات خاصة',
    methodType: 'الطريقة',
    serviceFee: 'الرسوم',
    closeQuotationPreview: 'إغلاق المعاينة',
    sendQuotationFinal: 'إرسال عرض السعر',
    pleaseSelectCustomerToPreview: 'يرجى اختيار عميل لمعاينة عرض السعر',
    
    // User Management Module
    greenModulesAssignedPermissions: 'الوحدات الخضراء تم تعيين صلاحيات لها. انقر على "إضافة صلاحية" لتعيين صلاحيات للوحدات غير المعينة.',
    tabControls: 'تحكم التبويبات',
    contentVisibility: 'رؤية المحتوى',
    userActions: 'إجراءات المستخدم',
    controlTabsVisibility: 'تحكم في التبويبات المرئية في واجهة الوحدة',
    manageContentDisplay: 'إدارة المحتوى والبيانات المعروضة للمستخدمين',
    defineUserActions: 'تحديد الإجراءات التي يمكن للمستخدمين القيام بها في هذه الوحدة',
    usersWillSeeTabs: 'المستخدمون سيرون هذه التبويبات في الوحدة',
    contentWillBeVisible: 'هذا المحتوى سيكون مرئياً للمستخدمين',
    usersCanPerformActions: 'المستخدمون يمكنهم تنفيذ هذه الإجراءات',
    moduleAccessDenied: 'تم رفض الوصول للوحدة',
    grantModuleAccessFirst: 'اعطِ صلاحية الوصول للوحدة أولاً لتكوين المميزات الفردية',
    permissionsSaved: 'تم حفظ الصلاحيات',
    allPermissionChangesSaved: 'تم حفظ جميع تغييرات الصلاحيات بنجاح.',
    savePermissionChanges: 'حفظ التغييرات',
    permissionsUpdated: 'تم تحديث الصلاحيات',
    modulePermissionsConfigured: 'تم تكوين صلاحيات الوحدة بنجاح.',
    saveConfiguration: 'حفظ التكوين',
    permissionRemovedMsg: 'تم حذف الصلاحية بنجاح.',
    failedToDeletePermission: 'فشل في حذف الصلاحية',
    manageModulePermissionsFor: 'إدارة صلاحيات الوحدة لـ',
    currentPermissions: 'الصلاحيات الحالية',
    module: 'الوحدة',
    access: 'الوصول',
    actionsList: 'الإجراءات',
    grantedStatus: 'مُمنوح',
    deniedStatus: 'مُرفوض',
    configure: 'تكوين',
    remove: 'إزالة',
    noPermissionsAssigned: 'لم يتم تعيين صلاحيات بعد',
    availableModules: 'الوحدات المتاحة',
    fullAccessGranted: 'تم منح الوصول الكامل',
    accessGrantedToAllModules: 'تم منح الوصول إلى جميع الوحدات الـ {{count}} في نظام تخطيط موارد المؤسسة.',
    grantAllModules: 'منح جميع الوحدات',
    modulesList: 'وحدات',
    configureModulePermissions: 'تكوين صلاحيات الوحدة',
    configureDetailedPermissionsFor: 'تكوين الصلاحيات التفصيلية لـ',
    moduleFor: 'وحدة لـ',
    availableFeatures: 'الميزات المتاحة',
    moduleAccessGranted: 'تم منح الوصول للوحدة',
    controlsVisibilityAndAccess: 'يتحكم في الرؤية والوصول لهذه الميزة',
    outOfCount: 'من',
    featuresEnabled: 'الميزات مُفعلة',
    
    confirmDeleteUser: 'هل أنت متأكد من حذف هذا المستخدم؟',
    
    // Module Descriptions (Arabic)
    dashboardDesc: 'نظرة عامة ولوحة التحكم الرئيسية والتحليلات',
    inventoryDesc: 'إدارة المخزون وتتبع المخزون',
    expensesDesc: 'تتبع وإدارة المصروفات',
    accountingDesc: 'الإدارة المالية والتقارير',
    suppliersDesc: 'إدارة الموردين والعلاقات',
    customersDesc: 'إدارة علاقات العملاء',
    createInvoiceDesc: 'إنشاء وإدارة الفواتير',
    createQuotationDesc: 'إنشاء عروض الأسعار والتسعير',
    invoiceHistoryDesc: 'عرض وإدارة تاريخ الفواتير',
    quotationHistoryDesc: 'عرض سجلات وتاريخ عروض الأسعار',
    orderManagementDesc: 'معالجة وتتبع الطلبات',
    ordersHistoryDesc: 'بيانات وسجلات الطلبات التاريخية',
    labelGeneratorDesc: 'إنشاء ملصقات المنتجات والشحن',
    reportsDesc: 'تقارير الأعمال والتحليلات',
    procurementDesc: 'إدارة المشتريات والتوريد',
    userManagementDesc: 'إدارة حسابات المستخدمين والأدوار',
    systemPreferencesDesc: 'تكوين النظام والإعدادات',
    
    // OrderManagement translations
    selectCustomer: 'اختر عميل...',
    searchCustomers: 'البحث عن العملاء...',
    noCustomerFound: 'لم يتم العثور على عميل.',
    batchNumber: 'رقم الدفعة',
    autoGenerated: 'مُولد تلقائياً',
    finalProduct: 'المنتج النهائي',
    describeFinalProduct: 'وصف المنتج النهائي',
    rawMaterials: 'المواد الخام',
    selectMaterial: 'اختر مادة',
    quantity: 'الكمية',
    unitPrice: 'سعر الوحدة',
    packaging: 'التعبئة والتغليف',
    selectPackaging: 'اختر التعبئة',
    additionalCosts: 'التكاليف الإضافية',
    transportationCost: 'تكلفة النقل',
    laborCost: 'تكلفة العمالة',
    equipmentCost: 'تكلفة المعدات',
    overheadCost: 'التكاليف العامة',
    createProductionOrder: 'إنشاء أمر إنتاج'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    
    // Update document direction and lang attribute
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const isRTL = language === 'ar';

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  useEffect(() => {
    // Set initial direction and lang
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};